baseURL: https://turtletree.github.io
languageCode: en-us
title: Vickie's Digital Garden
theme: "PaperMod"
author:
    name: "Vickie Liu"
    url: "https:://github.com/turtletree"
    avatar: "turtletree.png"
params:
    homeInfoParams:
        Title: I made it live 😎
        Content: This is my personal website with not much in it 🙃

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/turtletree"
        - name: "youtube"
          url: "https://www.youtube.com/"
        - name: "instagram"
          url: "https://www.instagram.com/vickieonthetree"
        #- name: "twitter"
         # url: "https://twitter.com/aryansawhney17"
        #- name: "kofi" 
         # url: "https://buymeacoffee.com/sawhney17"
    ShowReadingTime: true
    author: "Vickie Liu"
    feedlinks: true
    mobileMenu: true
    favicon: "favicon.ico"
    icon: "favicon.ico"
    image: "favicon.ico"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20
        - identifier: notes
          name: Notes
          url: /logseq-public
          weight: 20
